import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SidebarContextProvider from '@/context/sidebarContext'
import Sidebar from '@/components/Sidebar'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <SidebarContextProvider>
        <body className={inter.className}>
          <div className="sticky top-0"><Header /></div>
          <Sidebar />
          {children}
          <Footer />
        </body>
      </SidebarContextProvider>
    </html>
  )
}
